name: Deploy Static Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      run: |
        az login --username "${{ secrets.AZURE_USERNAME }}" --password "${{ secrets.AZURE_PASSWORD }}"

 
    # Set the subscription and resource group
    - name: Set Azure Context
      run: |
        az account set --subscription "${{ secrets.SUBSCRIPTION_ID }}"
        az group show --name staticwebsite || echo "Resource group not found."


    - name: Upload to Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{secrets.AZURE_STORAGE_NAME}} --account-key ${{ secrets.AZURE_STORAGE_KEY }} --auth-mode key --overwrite -d '$web' -s .
          
    - name: Purge CDN Endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "Staticwebsitehosting" --name "storagestaticwebsite" --resource-group "staticwebsite"

    - name: Logout from Azure
      run: az logout
      if: always()
